### ISSUE TITLE
Merci !

### ISSUE THREAD

**Issue by NLKLVL2** [flecoufle/node-red-linky#6]
Merci pour ton code ! Je fais partie de la majorité silencieuse mais je tenais a te remercier.
Sans vouloir abuser, si on pouvais avoir un End Point qui remonte les caractéristiques de la lignes PDM, heures pleines, heures creuses, etc... ce serait vraiment top et complet !

En tout cas bonne journée a toi.

**Comment by flecoufle** [comment]
Merci, je regarderai si une API permet d'avoir quelques informations intéressantes

**Comment by flecoufle** [comment]
La seule solution est que le client autorise l'accès à l'API Contract qui contient tout ce qu'il faudrait : HP/HC, tu peux remonter ton besoin sur l'API sous-jacente https://github.com/bokub/conso-api/issues
